name: branchLSTM
channels:
  - conda-forge
dependencies:
  - python=2.7.*
  - numpy=1.11.1
  - pip=9.0.3
  - pip:
      - backports.functools-lru-cache==1.5
      - boto==2.48.0
      - boto3==1.7.44
      - botocore==1.10.44
      - bz2file==0.98
      - certifi==2018.4.16
      - chardet==3.0.4
      - cycler==0.10.0
      - decorator==4.3.0
      - docutils==0.14
      - future==0.16.0
      - futures==3.2.0
      - gensim==1.0.0
      - hyperopt==0.1
      - idna==2.7
      - jmespath==0.9.3
      - kiwisolver==1.0.1
      - -e git+https://github.com/Lasagne/Lasagne.git@8772ebbbaf15951f2deb1bc2d76940ebd8ad2076#egg=Lasagne
      - matplotlib==2.2.2
      - networkx==1.11
      - nltk==3.2.4
      - nose==1.3.7
      - pymongo==3.6.1
      - pyparsing==2.2.0
      - python-dateutil==2.7.3
      - pytz==2018.5
      - requests==2.19.1
      - s3transfer==0.1.13
      - scikit-learn==0.18.1
      - scipy==1.1.0
      - six==1.11.0
      - smart-open==1.5.7
      - subprocess32==3.5.2
      - Theano==0.8.2
      - urllib3==1.23
